### ISSUE TITLE
US1 - Landing page

### ISSUE THREAD

**Issue by kevinldg** [kevinldg/upcycling-app#1]
## Value proposition
As a user

I want to access a list of 4 ideas, when i load the app

In order to have a general overview

## Description

![Image](https://github.com/kevinldg/upcycling-app/assets/68171149/4121a998-5bc4-4404-b0e3-32113ab23464)

## Acceptance criteria
- [x] The first 4 ideas (incl. image, title and hashtags) should directly appear to the user, when the app is loaded
- [x] A header is visible

## Tasks
- [x] Create dummy data for the ideas
- [x] Create landing/index Page
- [x] Create components: Header, Idea Card (with image, title and hashtags)
- [x] Fetch the data

**Comment by CJAkkuec** [comment]
Nice, job - I just have a couple of notes and one question:

> As a user, when I open the app,
> I want to access a list of 4 ideas, 
> In order to have a small overview

Why 4? 🤔 

> The first 4 ideas should be visible and displayed correctly
> ...

Perhaps it'd be beneficial to describe the features of the idea cards. Is there an image, a title, etc?

**Comment by kevinldg** [comment]
> Perhaps it'd be beneficial to describe the features of the idea cards. Is there an image, a title, etc?

Updated following lines. Is that what you meant?

> The first 4 ideas (incl. image, title and hashtags) should directly appear to the user, when the app is loaded
> Create components: Header, Idea Card (with image, title and hashtags)

Regarding your question:

> As a user, when I open the app,
> I want to access a list of 4 ideas,
> In order to have a small overview

> Why 4? 🤔

Just to have a small preview when loading the first page.
