### ISSUE TITLE
US9 - Database

### ISSUE THREAD

**Issue by kevinldg** [kevinldg/upcycling-app#10]
## Value proposition

As a developer
I want to be able to save data on an external server, 
so that I can interact with MongoDB though CRUD.

As a User 
I want my data to be saved permanently,
so that others can see my entries.

## Description

N/A

## Acceptance criteria

- [ ] I want to be able to save and update the data on MongoDB and handle the CRUD operations
- [ ] The data should persist after reloading the page

## Tasks

- [ ] Create a database on MongoDB
- [ ] Link to the database trough an .env file
- [ ] Set up the models and schema files
- [ ] Handle the GET, POST, PUT and DELETE Requests in their respective API files
- [ ] Save the MongoDB credentials in Vercel

**Comment by kristinwegener** [comment]
Hi :)
maybe as another task you could add: save the MongoDB credentials in Vercel (this problem occured to us and we were searching for ages, so maybe that helps..)

Maybe as a value for users: As a user I want my data to be saved permanently so that others can see my entries.

**Comment by Hendrik-Pils** [comment]
Thank you for your proposition, we will update the story!

**Comment by F-Kirchhoff** [comment]
Hey,
please add to the AC:
- that the data should be persisted after reloading the page

and specify which parts of the code need to change. You will need to add some api endpoints as well, so please specify them too and list what you need to create in them.

**Comment by F-Kirchhoff** [comment]
LGTM
