### ISSUE TITLE
US14 - Create User Profile

### ISSUE THREAD

**Issue by Hendrik-Pils** [kevinldg/upcycling-app#22]
## Value Proposition

As a User,
I want to be able to create a User Profile on a corresponding page,
so that the site functionality is exclusive to me.

## Acceptance Criteria

- [ ] On the nav bar, there is a profile page button.
- [ ] The button leads to a profile page.
- [ ] The dark mode button is moved to the profile page.

## Tasks

- [ ] Create the profile page button.
- [ ] Create the profile page.
- [ ] Add dark mode and settings to the profile page.

**Comment by jessicareinh** [comment]
The wireframes are missing, overall it is not detailed enough
