### ISSUE TITLE
US15 - Login

### ISSUE THREAD

**Issue by Hendrik-Pils** [kevinldg/upcycling-app#23]
## Value Proposition

As a User,
I want to be able to login to the reUse App,
so that the site functionality will be exclusive to me at this point.

## Acceptance Criteria

- [ ] A User Login with next/auth is created, so that you can Login with your GitHub profile.

## Tasks

- [ ] Create the User Login with next/auth.
- [ ] Implement Login with Github.

**Comment by kevinldg** [comment]
Note:

Two OAuth apps, each with one client id and one secret id have been created on GitHub. One for production, one for development.

Client ID, Secret ID (Production) -> Vercel
Client ID, Secret ID (Development) -> .env.local. File

The reason for this is that an OAuth app on GitHub only allows one callback URL.
