### ISSUE TITLE
US16 - Map (Location)

### ISSUE THREAD

**Issue by Hendrik-Pils** [kevinldg/upcycling-app#24]
## Value Proposition

As a User,
I want to be able to have List with my nearest upcycling Locations (e.g. community-based workplaces),
so that I am able to organize my upcycling efforts better.

## Acceptance Criteria

- [ ] There is a map page, where there is a list shown for the nearest locations.

## Tasks

- [ ] Create the map page button.
- [ ] Create the map page.
- [ ] Find a way to implement a map feature, where the nearest locations for upcycling are shown.
