### ISSUE TITLE
US17 - About page

### ISSUE THREAD

**Issue by kevinldg** [kevinldg/upcycling-app#28]
## Value proposition

As a user
I want to view a about page
In order to see the creator of the app and a link to their github profiles

and

I want to view the used technologies on the about page
In order to have a deeper understanding of how the app is built

## Description

N/A

## Acceptance criteria

- [ ] A about page is existing
- [ ] The about page is shown in the navigation with a corresponding icon
- [ ] The github avatar, name and a link to the github profile of each team member is listed on the about page
- [ ] The used technologies are shown in a list on the about page

## Tasks

- [ ] Create a new page "about.js"
- [ ] Create a TeamMemberCard component, including an image, a text (username) and a link (to github profile)
- [ ] Render a TeamMemberCard for each team member on the about page
- [ ] Create a unordered list for the used technologies and show it on the about page
