### ISSUE TITLE
US3 - Idea Form

### ISSUE THREAD

**Issue by jore-averbeck** [kevinldg/upcycling-app#3]
## Value proposition

As a User
I want to add ideas via a form to organize my upcycling project

## Description

![Image](https://github.com/gunsh0tzz/upcycling-app/assets/149486750/4a20bc90-68c8-4e30-b985-1518d7fc1d42)

## Acceptance criteria

- [ ] There is a form on a new page (Create page) where the user can add a idea
- [ ] The user can input things like title, image url, items, description, hashtags
- [ ] When the user clicks on the cancel button, he is redirected to the overview page

## Tasks

- [ ] Create Component: Form
- [ ] Handle form submit: Add submitted data to the data array and redirect user to the overview page
- [ ] Create a cancel button that redirects to the overview page

**Comment by F-Kirchhoff** [comment]
Hey!
very nice user story so far. Please update these points:
- remove the concrete solution inside the value proposition: "a form component". The value proposition describes the need of the user not the solution for it.
- where is the form exactly? is it a new "create" page? If so state it in the acceptance criteria.
- please use more descriptive wording for the acceptance criteria: "when the user clicks the back button, the is redirected to the overview page" and "if the user clicks the submit button, a new card with the specified information is created and the user is redirected to the overview page"
- please provide more information to thte tasks: how do you handle the submit? Do you need a function for adding elements to your data array? Do you need another page component?

**Comment by kevinldg** [comment]
Hey, thx for your feedback! The user story was updated 👍

**Comment by CJAkkuec** [comment]
>  When the user clicks on the back button, he is redirected to the overview page
This should probably say "cancel button", right? :)

**Comment by kevinldg** [comment]
> This should probably say "cancel button", right? :)

That's right, corrected!
