### ISSUE TITLE
US18 - Upload Image

### ISSUE THREAD

**Issue by jore-averbeck** [kevinldg/upcycling-app#30]
## Value proposition

As a user
I want to be able to upload images 
In order to use my own images from my gallery.

## Acceptance criteria

- [ ] An upload button for the image is added in the form where the user can create a new entry
- [ ] The user is informed that only certain image formates are allowed (png, jpg, jpeg)
- [ ] Clicking the upload button opens up a "picker" where the user can select an image from they device
- [ ] Afterwards the name of the selected image is displayed in the form 
- [ ] After creating a new entry the image is visible 

## Tasks

- [ ] sign up to cloudinary 
- [ ] retrieve API Key and API Secret 
- [ ] install cloudinary (npm install cloudinary)
- [ ] add the attributes accept= "png, jpg, jpeg" to the image input element
- [ ] create a remove "X" Button to remove the selected image 
- [ ] cloudinary is used to store the image(s)
