### ISSUE TITLE
US19 - Exclusive favorite feature

### ISSUE THREAD

**Issue by kevinldg** [kevinldg/upcycling-app#31]
## Value proposition

As a user
I want to only have access to my favorite ideas when i am authenticated as my person
In order to make sure, that only i have access to my favorite ideas

## Description

N/A

## Acceptance criteria

- [ ] When a user is not authenticated, the favorite page can not be accessed (redirect to landing page)
- [ ] When a user is not authenticated, the favorite icon in the navigation is not shown
- [ ] When a user is not authenticated, ideas can not be marked as favorite

- [ ] When a user is authenticated, the favorite icon in the navigation is shown
- [ ] When a user is authenticated, ideas can be marked as favorite

- [ ] The favorite page is only showing ideas, that i marked as favorite when i was authenticated

## Tasks

- [ ] TODO

**Comment by Roland-Hufnagel** [comment]
Good userstory and I like the way you describe the different behaviour in the AC. But please decide to write a userstory OR a developerstory. Keep in mind: Writing a userstory that adds a value for the user means lots of money and budget for the develperteam (👍 great) because the customer wants it. Writing a good developerstory is unimportant for the customer. He won't pay money for that! That means you won't get much time or budget for that. 
You can add some task for protecting the backend.

**Comment by Roland-Hufnagel** [comment]
That looks good 👍

**Comment by kevinldg** [comment]
Edit:
When an unauthenticated user tries to access a page he's not authorized to, a text "Access denied. You have to be logged in to view this page." will be displayed instead of getting redirected to the landing page.

When an unauthenticated user tries to access a backend route he's not authorized to, an error http code 401 will be returned instead of 403.
