### ISSUE TITLE
US20 - Cloudinary Image Cropping

### ISSUE THREAD

**Issue by Hendrik-Pils** [kevinldg/upcycling-app#35]
## Value proposition

As a user,
I want to be able to crop the pictures I am uploading to the app,
In order to have more control over how the uploaded image is displayed.

## Acceptance criteria
- [ ] There is a preview image displayed, when i upload an image.
- [ ] The image can be cropped to only contain the necessary information.

## Tasks

- [ ] Modify the Cloudinary functions to contain the code for displaying a preview image.
- [ ] Research the function to crop an uploaded image.
- [ ] Add the feature to your modified code.
