### ISSUE TITLE
US21 - Accessibility features

### ISSUE THREAD

**Issue by Hendrik-Pils** [kevinldg/upcycling-app#36]
## Value proposition

As a user
I want the app to be more accessible for screen-readers,
so that persons using these, can navigate the app with ease.

## Acceptance criteria

- [ ] The whole app has a higher accessibility for screen-readers.

## Tasks

- [ ] Make every image have an alt-attribute.
- [ ] Make every icon have an aria-label.
- [ ] Give some relevant div's aria-labels.

**Comment by jessicareinh** [comment]
looks good! ✌️
