### ISSUE TITLE
DS2 - Delete Images from Cloudinary

### ISSUE THREAD

**Issue by Hendrik-Pils** [kevinldg/upcycling-app#37]
## Value proposition

As a developer
I want to delete an uploaded image from Cloudinary
In order to clean up Cloudinary and to have everything tidy.

## Acceptance criteria

- [ ] Images can be deleted from Cloudinary.

## Tasks

- [ ] Research on how to delete Images from Cloudinary.
- [ ] Modify the Cloudinary Code, so that uploaded images can be deleted.
