### ISSUE TITLE
US22 - Loading Animation

### ISSUE THREAD

**Issue by Hendrik-Pils** [kevinldg/upcycling-app#38]
## Value proposition

As a user,
I want to see a loading animation, whenever the app loads something,
In order to have a nicer user experience.

## Acceptance criteria

- [ ] Whenever the site loads from the database, a loading animation is displayed.

## Tasks

- [ ] Use framer-motion for the loading animation.
- [ ] Research framer-motion implementation.
- [ ] Implement framer-motion with UseEffect and UseState.
- [ ] Set a timer for the loading animation.

**Comment by kabaskill** [comment]
Setting an arbitrary timer for only showing the animation doesn't improve the UX in my opinion. You could consider that but otherwise looks good to me.

**Comment by SarahJoyceMorgen** [comment]
> Setting an arbitrary timer for only showing the animation doesn't improve the UX in my opinion. You could consider that but otherwise looks good to me.


Thank you, we will discuss again whether the loading animation will be displayed only when an extended loading time is actually necessary.
